application: devfesthh
version: 9
runtime: python27
api_version: 1
threadsafe: yes

skip_files:
- ^bower_components/.*
- ^data/.*
- ^build/unbundled/.*
- ^images/.*
- ^scripts/.*
- ^src/.*
- ^test/.*
- ^build/bundled/bower_components/(.*/)?.*\.md$
- ^build/bundled/bower_components/(.*/)?demo/.*
- ^build/bundled/bower_components/(.*/)?tests?/.*
- ^build/bundled/bower_components/(.*/)?bower.json$
- ^build/bundled/bower_components/(.*/)?package.json$
- ^build/bundled/bower_components/(.*/)?LICENSE$
- ^build/bundled/bower_components/(.*/)?COPYING$
- ^build/bundled/bower_components/(.*/)?Makefile$
- ^build/bundled/bower_components/(.*/)?.*\.map$
- (.*/)?.git/.*

handlers:
- url: /bower_components
  static_dir: build/bundled/bower_components
  secure: always

- url: /images
  static_dir: build/bundled/images
  secure: always

- url: /src
  static_dir: build/bundled/src
  secure: always

- url: /scripts
  static_dir: build/bundled/scripts
  secure: always

- url: /data
  static_dir: build/bundled/data
  secure: always

- url: /service-worker.js
  static_files: build/bundled/service-worker.js
  upload: build/bundled/service-worker.js
  secure: always

- url: /manifest.json
  static_files: build/bundled/manifest.json
  upload: build/bundled/manifest.json
  secure: always

- url: /.*
  static_files: build/bundled/index.html
  upload: build/bundled/index.html
  secure: always

